name: shoplift
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0-beta+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+4 # Add this line for the image_picker package
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_database: ^10.5.7
  firebase_storage: ^11.0.16
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  google_fonts: ^4.0.5
  email_validator: ^2.1.17
  image: ^4.0.15
  http: ^1.3.0
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  assets:
      - assets/fonts/fonts/

  uses-material-design: true

  fonts:
    - family: Kalam
      fonts:
        - asset: assets/fonts/fonts/kalam-Light.ttf
          weight: 300
        - asset: assets/fonts/fonts/kalam-bold.ttf
          weight: 700

    - family: Gabarito
      fonts:
        - asset: assets/fonts/fonts/Gabarito-Regular.ttf
          weight: 400
        - asset: assets/fonts/fonts/Gabarito-Medium.ttf
          weight: 500
        - asset: assets/fonts/fonts/Gabarito-Bold.ttf
          weight: 700

    - family: CircularStd
      fonts:
        - asset: assets/fonts/fonts/CircularStd-Regular.ttf
          weight: 400
        - asset: assets/fonts/fonts/CircularStd-Medium.ttf
          weight: 500
        - asset: assets/fonts/fonts/CircularStd-Bold.ttf
          weight: 700

