// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3V8a9OirCHYIwHqeQFie7mfXLDCKxcys',
    appId: '1:538334935454:web:484dbf156d73949f187e8f',
    messagingSenderId: '538334935454',
    projectId: 'shoplift-287c5',
    authDomain: 'shoplift-287c5.firebaseapp.com',
    storageBucket: 'shoplift-287c5.firebasestorage.app',
    measurementId: 'G-97M3391EYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkIJIz2656lsBvFUxoSt-gzUvZcx1KWAo',
    appId: '1:538334935454:android:1d21092df9afa5fa187e8f',
    messagingSenderId: '538334935454',
    projectId: 'shoplift-287c5',
    storageBucket: 'shoplift-287c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl7fTBbmbF7Jk2_QjSUX28fVs1DdlWZB4',
    appId: '1:538334935454:ios:c7705bb229406ea8187e8f',
    messagingSenderId: '538334935454',
    projectId: 'shoplift-287c5',
    storageBucket: 'shoplift-287c5.firebasestorage.app',
    iosBundleId: 'com.example.shoplift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl7fTBbmbF7Jk2_QjSUX28fVs1DdlWZB4',
    appId: '1:538334935454:ios:c7705bb229406ea8187e8f',
    messagingSenderId: '538334935454',
    projectId: 'shoplift-287c5',
    storageBucket: 'shoplift-287c5.firebasestorage.app',
    iosBundleId: 'com.example.shoplift',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3V8a9OirCHYIwHqeQFie7mfXLDCKxcys',
    appId: '1:538334935454:web:a491514ff178b2d3187e8f',
    messagingSenderId: '538334935454',
    projectId: 'shoplift-287c5',
    authDomain: 'shoplift-287c5.firebaseapp.com',
    storageBucket: 'shoplift-287c5.firebasestorage.app',
    measurementId: 'G-7GGZ8PT98Q',
  );
}
